name: CI-CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Setup Snowflake Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_organization: ${{ secrets.SNOWFLAKE_ORGANIZATION }}
      TF_VAR_user: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_role: ${{ secrets.SNOWFLAKE_ROLE }}
      TF_VAR_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      TF_VAR_dbt_user_password: ${{ secrets.DBT_PASSWORD }}

      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -input=false \
            -var "account=${TF_VAR_account}" \
            -var "organization=${TF_VAR_organization}" \
            -var "user=${TF_VAR_user}" \
            -var "password=${TF_VAR_password}" \
            -var "role=${TF_VAR_role}" \
            -var "warehouse=${TF_VAR_warehouse}"
            -var "dbt_user_password=${TF_VAR_dbt_user_password}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve -input=false \
            -var "account=${TF_VAR_account}" \
            -var "organization=${TF_VAR_organization}" \
            -var "user=${TF_VAR_user}" \
            -var "password=${TF_VAR_password}" \
            -var "role=${TF_VAR_role}" \
            -var "warehouse=${TF_VAR_warehouse}"
            -var "dbt_user_password=${TF_VAR_dbt_user_password}"

